<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0-browser</TargetFramework>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <RootNamespace>SukeFlow.Browser</RootNamespace>
        <AssemblyName>SukeFlow.Browser</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" Version="12.1.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SukeFlow.Core\SukeFlow.Core.csproj"/>
    </ItemGroup>
</Project>
